### ISSUE TITLE
Minimal required EPrints version?

### ISSUE THREAD

**Issue by ACz-UniBi** [photomedia/EPrintsOpenAIRE#1]
Dear,

a short quick question, which is the minimal required EPrints version of this plugin?
I would like to add this great compatibility to the Overview at:

https://docs.google.com/spreadsheets/d/1_TQzbMf1jz-YEgatt76IMe-MBbt28g-1_N7j_GZyoPc/edit#

Thanks in advance, Andreas

**Comment by photomedia** [comment]
Hi Andreas,
Thank you for the question.  I developed the plugin using EPrints 3.3.12.  
It is a relatively early version of the export plugin implementation at this point.  I don't see anything that might cause issues on other version of EPrints, both earlier and later versions of EPrints 3.3 and 3.4, but it needs to be tested still to confirm with certainty.

**Comment by ACz-UniBi** [comment]
Hi Tomasz,

thank you very much and also for your efforts for this contribution! 
I'll link this repository from the "Overview of OpenAIRE Guidelines&UsageCounts support by Repositories-Platforms-Versions" sheet.

All the best, Andreas
