### ISSUE TITLE
Unallowed value for identifierType (URI)

### ISSUE THREAD

**Issue by jploski** [photomedia/EPrintsOpenAIRE#2]
OpenAIRE help desk pointed out today that we are exporting an unallowed value "URI" for the identifierType attribute of datacite:identifier. For a list of allowed values see https://guidelines.openaire.eu/en/latest/data/field_identifier.html#d-identifiertype ("URL" is allowed; "URI" is not).

The following line in the plugin is causing this bug: https://github.com/eprintsug/EPrintsOpenAIRE/blob/main/lib/plugins/EPrints/Plugin/Export/OPENAIRE.pm#L324

**Comment by ACz-UniBi** [comment]
Dear @jploski ,

thank you for your effort. Will this change mark each record as updated or should OpenAIRE re-harvesting each repository which implements this fix?

Best, Andreas

**Comment by jploski** [comment]
> Dear @jploski ,
> 
> thank you for your effort. Will this change mark each record as updated or should OpenAIRE re-harvesting each repository which implements this fix?

This change will not mark each record as updated; it only changes the export format. So I'm afraid you will have to initiate the reharvesting of each repo which implements it yourself if this error made the records unprocessable befor. But since there may be many affected repositories, it may be easier to apply some "temporary" workaround to harvesting code which tolerates the unallowed "URI" identifier from EPrints and processes it as if it was "URL".

**Comment by photomedia** [comment]
thank you @jploski , it looks like changing [that ](https://github.com/eprintsug/EPrintsOpenAIRE/blob/main/lib/plugins/EPrints/Plugin/Export/OPENAIRE.pm#L324) to "URL" from "URI" should solve the issue, right?

**Comment by jploski** [comment]
> thank you @jploski , it looks like changing [that ](https://github.com/eprintsug/EPrintsOpenAIRE/blob/main/lib/plugins/EPrints/Plugin/Export/OPENAIRE.pm#L324) to "URL" from "URI" should solve the issue, right?

Yes, that is exactly the fix I applied for our repository.

**Comment by photomedia** [comment]
That's great, thanks.  I pushed the fix, and updated the bazaar package.
